name: rpsp_iasd
description: Reavivados por su palabra IASD

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 4.1.0+65

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.1.0
  
  # UI & Animations
  cached_network_image: ^3.2.0
  auto_size_text: ^3.0.0
  animations: ^2.0.2
  lottie: ^3.0.0
  shimmer: ^3.0.0
  flutter_displaymode: ^0.6.0
  google_nav_bar: ^5.0.5
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  
  # Utils & Logic
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.4.9
  adaptive_theme: ^3.4.1
  fluttertoast: ^8.2.2
  path_provider: ^2.0.9
  validators: ^3.0.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  url_launcher: ^6.0.20
  internet_connection_checker: ^3.0.1
  app_settings: ^6.1.1
  package_info_plus: ^8.0.0
  sliver_tools: ^0.2.5
  in_app_review: ^2.0.10
  uuid: ^4.1.0
  path: ^1.8.1
  loader_overlay: ^5.0.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  timeago: ^3.3.0
  html_unescape: ^2.0.0
  form_field_validator: ^1.1.0
  app_links: ^6.1.1
  crypto: ^3.0.3
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.4.9
  logger: ^2.2.0
  
  # Storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # HTML & Markdown
  flutter_html: 3.0.0
  flutter_html_all: 3.0.0
  webview_flutter: ^4.10.0
  html: ^0.15.4
  markdown_widget: ^2.3.2+6
  flutter_syntax_view: ^4.1.0
  
  # Firebase & Auth
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^7.0.1
  
  # Networking
  dio: ^5.0.3
  dio_cache_interceptor: ^4.0.3
  
  # Others
  onesignal_flutter: ^5.2.1
  last_pod_player: ^0.0.5
  in_app_update: ^4.2.3
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.1.6
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1F2935"
  image: "assets/others/splash_logo_light.png"
  image_dark: "assets/others/splash_logo_dark.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/others/logo.png"
  web:
    generate: false
  windows: 
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/others/
    - assets/animations/
    - assets/svgs/
    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500

dependency_overrides:
  sqflite_android: 2.4.1
